name: workflows

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    uses: co-cddo/gds-idea-workflows-catalogue/.github/workflows/pre-commit.yml@main
    permissions:
      contents: read
    with:
      terraform_setup: true
